name: Android

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gettext
      run: sudo apt-get update && sudo apt-get install -y gettext

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Install CMake
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.31.0"

    - name: Cache CMake build folder
      uses: actions/cache@v4
      with:
        path: android-project/app/.cxx
        key: ${{ github.workflow }}-v5-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v5-

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cd android-project && ./gradlew assembleDebug

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-debug.apk
        path: android-project/app/build/outputs/apk/debug/app-debug.apk

    - name: Clean up artifacts
      run: rm -rf android-project/app/build/outputs
