name: Miyoo Mini Release Build

on:
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  miyoo-mini:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name:  Install toolchain
      working-directory: ${{github.workspace}}
      run: sudo Packaging/miyoo_mini/setup_toolchain.sh

    - name:  Build
      working-directory: ${{github.workspace}}
      run: Packaging/miyoo_mini/build.sh

    - name: Upload-OnionOS-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-miyoo-mini-onion-os.zip
        path: build-miyoo-mini/devilutionx-miyoo-mini-onion-os.zip

    - name: Upload-miniUI-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-miyoo-mini-miniui.zip
        path: build-miyoo-mini/devilutionx-miyoo-mini-miniui.zip

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        file: "build-miyoo-mini/devilutionx-*.zip"
        file_glob: true
        overwrite: true
