name: PS4

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ps4:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y pacman-package-manager wget cmake git gettext smpq && \
        sudo tee -a /etc/pacman.conf > /dev/null <<TEXT
        [pacbrew]
        SigLevel = Optional TrustAll
        Server = https://pacman.mydedibox.fr/pacbrew/packages/
        TEXT
    - name: Setup pacman packages
      run: |
        sudo pacman --noconfirm -Sy && \
        sudo pacman --noconfirm -S ps4-openorbis ps4-openorbis-portlibs && \
        echo "#include <endian.h>" | sudo tee /opt/pacbrew/ps4/openorbis/include/sys/endian.h

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: Packaging/ps4/build.sh

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-ps4.pkg
        path: build-ps4/devilutionx.pkg

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        asset_name: devilutionx-ps4.pkg
        file: build-ps4/devilutionx.pkg
        overwrite: true
