---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    login_success:
      type: object
      properties:
        api_token:
          type: string
        refresh_token:
          type: string
        user:
          id:
            type: integer
          display_name:
            type: string
          email:
            type: string
          token_expires_at:
            type: datetime
          refresh_token_expires_at:
            type: datetime
    login_failure:
      type: object
      properties:
        message:
          type: string
    sign_out:
      type: object
      properties:
        message:
          type: string
paths:
  "/api/v1/users/sign_in":
    post:
      summary: Signs in a user
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: user signed in
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/login_success"
        '401':
          description: invalid credentials
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/login_failure"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/users/sign_out":
    delete:
      summary: Signs out a user
      tags:
      - Sessions
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user signed out
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/sign_out"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/sign_out"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
