name: Extract and Validate Document ⚙️
description: Extract the document and validate the XML against the schema.

runs:
    using: composite
    steps:
        - name: Extract Word Document
          shell: bash
          run: npm run extract
        - name: Validate XML
          uses: ChristophWurst/xmllint-action@v1
          with:
              xml-file: build/extracted-doc/word/document.xml
              xml-schema-file: ooxml-schemas/microsoft/wml-2010.xsd
