version: 1.0.{build}
branches:
  only:
  - master
image: Ubuntu2204

init:
  # as its not possible to use docker as source image, we will install everything in init step
  - >
    sudo apt-get update --allow-releaseinfo-change &&
    sudo apt-get install -y g++-mingw-w64-x86-64 g++-mingw-w64-i686 unzip wget man2html-base groff

# we are building nsis 3.10 because one from ububtu 22.04 is impacted by 
# https://linux.debian.bugs.dist.narkive.com/x9BPoQjZ/bug-1050288-nsis-3-08-3-bookworm-generates-bogus-relocation-information-regression
before_build:
- cd $HOME
- wget 'https://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128-dll.zip' && unzip -d zlib zlib128-dll.zip
- wget https://prdownloads.sourceforge.net/nsis/nsis-3.10-src.tar.bz2 && tar -xf nsis-3.10-src.tar.bz2
- sudo apt-get install -y scons binutils-mingw-w64-i686 zlib1g-dev libcppunit-dev
- cd nsis-3.10-src && sudo scons -j `nproc` ZLIB_W32=$HOME/zlib SKIPUTILS="NSIS Menu" NSIS_CONFIG_LOG=yes build install && cd $APPVEYOR_BUILD_FOLDER

build_script:
- cd smartmontools
- export SOURCE_DATE_EPOCH=$(git log -1 --format="%at")
- SM_VER=$(grep -E 'AC_INIT\(\[smartmontools\]' configure.ac|awk -F, '{print $2}'|tr -d '[]')
- sh: "SVNREV=$(git log -1|grep -oP 'git-svn-id: http://svn.code.sf.net/p/smartmontools/code/trunk@(\\d+)'|awk -F@ '{print $2}')"
- BUILD_INFO='"(AppVeyor)"'
- 'echo "Starting build: SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}, SM_VER: ${SM_VER}, SVNREV: ${SVNREV}"'
- ./autogen.sh && mkdir build && cd build
- ../configure build_alias=$(../config.guess) host_alias=i686-w64-mingw32 SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
- make -j BUILD_INFO="$BUILD_INFO" && make distdir-win32 && cd .. && mkdir build64 && cd build64
- ../configure build_alias=$(../config.guess) host_alias=x86_64-w64-mingw32 SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
- make -j BUILD_INFO="$BUILD_INFO" && make distdir-win32
- cd ../build && dest="smartmontools-win32-setup-${SM_VER}-r${SVNREV}.exe"
- make BUILD_INFO="$BUILD_INFO" builddir_win64=../build64 distinst_win32="$dest" installer-win32
- sha256sum *.exe

artifacts:
- path: smartmontools/build/smartmontools-win32-setup-*.exe

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/0924a018-22d7-47ea-b10c-7c84c08e8d55/Integrations/AppVeyor?ProjectSlug=smartmontools&SigningPolicySlug=release-signing
  authorization:
     secure: Y7K0hTnpfEyXhOI/cG1URZwss24IjRECus4em8YscdJ73ujuXg/CRkdBa0eOoAZc7hUa+qo6rGOy/ii9iHE0zA==
